### ISSUE TITLE
代码中是否有一部分来源于百度开源的 NCRF？

### ISSUE THREAD

**Issue by Lotus-95** [ilikewind/CAMELYON#21]
您好，请问您的代码中是否有一部分来自于 NCRF？因为我看到有些代码是完全一致的，我想知道这些代码的来源？感谢。

**Comment by Lotus-95** [comment]
https://github.com/baidu-research/NCRF

**Comment by ilikewind** [comment]
> https://github.com/baidu-research/NCRF

对，参考了
